name: Deploy Project

on:
  push:
    branches:
      - main  # Chạy workflow khi có thay đổi trên nhánh chính

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước check-out mã nguồn
      - name: Check out the repository
        uses: actions/checkout@v2

      # Thiết lập Node.js phiên bản mới nhất
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Hoặc phiên bản node.js mà bạn đang sử dụng

      # Cài đặt các dependencies
      - name: Install dependencies
        run: |
          npm install
          npm install --force

      # Chạy build
      - name: Build project
        run: npm run dev

      # Tùy chọn: Deploy lên server hoặc các nền tảng cloud khác nếu cần
      # Thêm bước deploy ở đây nếu có, ví dụ: Firebase, Vercel, Netlify...
      # - name: Deploy to Firebase Hosting
      #   run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
